version: ">= 0.16.0, < 1.0.0"

formatter: markdown table

content: |-
  # Terraform Module Documentation

  {{ .Header }}

  {{ include "docs/terraform-header.md" }}

  ## Requirements

  {{ .Requirements }}

  ## Providers

  {{ .Providers }}

  ## Modules

  {{ .Modules }}

  ## Resources

  {{ .Resources }}

  ## Inputs

  {{ .Inputs }}

  ## Outputs

  {{ .Outputs }}

  {{ if eq .Path "terraform" }}
  ## Examples

  ```hcl
  {{ include "examples/basic/main.tf" }}
  ```
  {{ end }}

  {{ .Footer }}

output:
  file: "README.md"
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
